#!/usr/bin/env bash
# Generate a host target's ignored entry namespace before Shadow discovers the
# module graph, then build it with this checkout's pinned Shadow executable.

set -euo pipefail

repo_root="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$repo_root"

usage() {
  printf 'Usage: %s <opencode-plugin|mcp-server|claude-server|all> [...]\n' "$0" >&2
}

fail() {
  printf '[muse host build] %s\n' "$*" >&2
  exit 64
}

if (($# == 0)); then
  usage
  exit 64
fi

if (($# > 1)); then
  for target in "$@"; do
    [[ "$target" != all ]] || fail "'all' cannot be combined with another target"
  done
fi

targets=("$@")
if [[ "${targets[0]}" == all ]]; then
  targets=(opencode-plugin mcp-server claude-server)
fi

# Validate the complete request before probing or invoking any build tool.
for target in "${targets[@]}"; do
  case "$target" in
    opencode-plugin|mcp-server|claude-server) ;;
    *)
      usage
      fail "unsupported target: $target"
      ;;
  esac
done

command -v clojure >/dev/null 2>&1 || fail "missing prerequisite: clojure"
command -v node >/dev/null 2>&1 || fail "missing prerequisite: node"

shadow="$repo_root/node_modules/.bin/shadow-cljs"
[[ -x "$shadow" ]] || fail "missing pinned Shadow executable; run npm ci first"

# The generic MCP and Claude hooks each own a complete one-server document, so
# every MCP-producing request must preserve registrations that are not rebuilt,
# accumulate the documents generated by this request, publish their union to
# the configured MCP destination after each build, and keep a target-to-name
# producer-and-target ownership map so a rebuilt target can retire only its
# own checkout's old registration in a registry shared by several checkouts.
mcp_target_count=0
mcp_requested_targets=()
for target in "${targets[@]}"; do
  case "$target" in
    mcp-server|claude-server)
      mcp_target_count=$((mcp_target_count + 1))
      mcp_requested_targets+=("$target")
      ;;
  esac
done

mcp_registry=""
generated_mcp_registry=""
mcp_generated_output=""
mcp_ownership=""
mcp_original_registry=""
mcp_original_ownership=""
mcp_original_registry_present=0
mcp_original_ownership_present=0
mcp_state_restore_ready=0
mcp_state_publication_started=0
mcp_request_transaction_active=0
mcp_public_registry=""
mcp_resolved_destination=""
mcp_registry_dir=""
mcp_registry_dir_identity=""
mcp_producer_id=""
mcp_producer_file="$repo_root/.muse-host-targets-producer-id"
mcp_ownership_alias=""
mcp_ownership_file=""
mcp_ownership_dir=""
mcp_ownership_dir_identity=""
mcp_lock_dir=""
mcp_lock_owner=""
mcp_lock_acquired=0
mcp_lock_identity=""
mcp_legacy_relative_migration=0
mcp_transaction_file=""
mcp_transaction_alias=""
mcp_transaction_record=""
mcp_recovery_registry=""
mcp_recovery_ownership=""

atomic_publish() {
  local source="$1"
  local destination="$2"
  local new_mode="${3-}"
  local publish_destination="$destination"
  local publish_dir
  local resolved
  local staged

  # Callers bind aliases to their ultimate target before snapshotting. Never
  # follow a link introduced after that boundary: rename may replace the bound
  # pathname, but publication must not be redirected to a substituted target.
  mcp_destination_namespace_bindings_match "$publish_destination" || return 1
  resolved="$(canonicalize_mcp_destination "$publish_destination")" || return 1
  [[ "$resolved" == "$publish_destination" ]] || return 1
  [[ ! -L "$publish_destination" ]] || return 1
  [[ ! -e "$publish_destination" || -f "$publish_destination" ]] || return 1
  publish_dir="$(dirname "$publish_destination")"
  staged="$(mktemp "$publish_dir/.muse-host-targets.publish.XXXXXX")" || return 1
  if ! cp -- "$source" "$staged"; then
    rm -f -- "$staged"
    return 1
  fi
  if [[ -e "$publish_destination" ]]; then
    if ! node --input-type=module - "$publish_destination" <<'NODE'
import {lstatSync} from "node:fs";

const [destination] = process.argv.slice(2);
const existing = lstatSync(destination);
if (!existing.isFile() || existing.isSymbolicLink()) {
  throw new Error(`${destination} changed to a nonregular destination after binding`);
}
const uid = process.getuid();
if (existing.uid !== uid) {
  throw new Error(`${destination} changed to cross-user ownership after preflight`);
}
if (existing.gid !== process.getgid() && !process.getgroups().includes(existing.gid)) {
  throw new Error(`${destination} changed to an unavailable group after preflight`);
}
NODE
    then
      rm -f -- "$staged"
      return 1
    fi
    if ! cp --attributes-only --preserve=all --no-preserve=timestamps \
      -- "$publish_destination" "$staged"; then
      rm -f -- "$staged"
      return 1
    fi
  elif ! node --input-type=module - "$staged" "$new_mode" <<'NODE'
import {chmodSync} from "node:fs";

const [staged, requestedMode] = process.argv.slice(2);
const mode = requestedMode.length > 0
  ? Number.parseInt(requestedMode, 8)
  : 0o666 & ~process.umask();
if (!Number.isInteger(mode)) throw new Error(`invalid staged mode: ${requestedMode}`);
chmodSync(staged, mode);
NODE
  then
    rm -f -- "$staged"
    return 1
  fi
  if ! sync -f -- "$staged"; then
    rm -f -- "$staged"
    return 1
  fi
  if ! mcp_destination_namespace_bindings_match "$publish_destination"; then
    rm -f -- "$staged"
    return 1
  fi
  resolved="$(canonicalize_mcp_destination "$publish_destination")" || {
    rm -f -- "$staged"
    return 1
  }
  if [[ "$resolved" != "$publish_destination" ]]; then
    rm -f -- "$staged"
    return 1
  fi
  if ! mv -f -- "$staged" "$publish_destination"; then
    rm -f -- "$staged"
    return 1
  fi
  sync -f -- "$publish_dir"
}

canonicalize_mcp_destination() {
  local configured="$1"

  mkdir -p -- "$(dirname "$configured")"
  node --input-type=module - "$configured" <<'NODE'
import {lstatSync, readlinkSync, realpathSync} from "node:fs";
import {basename, dirname, join, resolve} from "node:path";

const [configured] = process.argv.slice(2);
function canonicalize(path, seen = new Set()) {
  const absolute = resolve(path);
  if (seen.has(absolute)) throw new Error(`destination symlink cycle: ${absolute}`);
  seen.add(absolute);
  const existing = lstatSync(absolute, {throwIfNoEntry: false});
  if (!existing) {
    return join(realpathSync(dirname(absolute)), basename(absolute));
  }
  if (existing.isSymbolicLink()) {
    return canonicalize(resolve(dirname(absolute), readlinkSync(absolute)), seen);
  }
  return realpathSync(absolute);
}
process.stdout.write(canonicalize(configured));
NODE
}

directory_identity() {
  local directory="$1"

  node --input-type=module - "$directory" <<'NODE'
import {lstatSync} from "node:fs";

const [directory] = process.argv.slice(2);
const metadata = lstatSync(directory, {bigint: true});
if (!metadata.isDirectory() || metadata.isSymbolicLink()) {
  throw new Error(`${directory} is not a bound physical directory`);
}
process.stdout.write(`${metadata.dev}:${metadata.ino}`);
NODE
}

resolve_mcp_producer_identity() {
  node --input-type=module - "$mcp_producer_file" "$repo_root" <<'NODE'
import {randomBytes} from "node:crypto";
import {
  chmodSync,
  closeSync,
  fsyncSync,
  linkSync,
  lstatSync,
  openSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";

const [identityPath, root] = process.argv.slice(2);
const temporaryPath = `${identityPath}.${process.pid}.${randomBytes(8).toString("hex")}.tmp`;

function readIdentity() {
  const metadata = lstatSync(identityPath, {throwIfNoEntry: false});
  if (!metadata) return null;
  if (!metadata.isFile() || metadata.isSymbolicLink()) {
    throw new Error(`${identityPath} is not a regular identity file`);
  }
  if (metadata.uid !== process.getuid()) {
    throw new Error(`${identityPath} is owned by uid ${metadata.uid}`);
  }
  if ((metadata.mode & 0o777) !== 0o600) {
    throw new Error(`${identityPath} must use mode 0600`);
  }
  const value = readFileSync(identityPath, "utf8");
  if (!/^[0-9a-f]{64}\n$/.test(value) || /^0{64}\n$/.test(value)) {
    throw new Error(`${identityPath} does not contain one valid producer identity`);
  }
  return value.slice(0, -1);
}

let identity = readIdentity();
if (!identity) {
  try {
    let generated;
    do {
      generated = randomBytes(32).toString("hex");
    } while (/^0{64}$/.test(generated));
    writeFileSync(temporaryPath, `${generated}\n`, {
      flag: "wx",
      mode: 0o600,
    });
    chmodSync(temporaryPath, 0o600);
    const temporary = openSync(temporaryPath, "r");
    try {
      fsyncSync(temporary);
    } finally {
      closeSync(temporary);
    }
    try {
      linkSync(temporaryPath, identityPath);
    } catch (error) {
      if (error?.code !== "EEXIST") throw error;
    }
  } finally {
    try {
      unlinkSync(temporaryPath);
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
  }
  identity = readIdentity();
}
const directory = openSync(root, "r");
try {
  fsyncSync(directory);
} finally {
  closeSync(directory);
}
process.stdout.write(identity);
NODE
}

resolve_mcp_target_destination() {
  local target="$1"
  local configured
  local resolver

  case "$target" in
    mcp-server)
      resolver="eta-mu.mcp.build/mcp-config-path"
      ;;
    claude-server)
      resolver="eta-mu.claude.build/mcp-config-path"
      ;;
    *)
      fail "cannot resolve an MCP destination for target: $target"
      ;;
  esac
  if ! configured="$(clojure -M -e \
    "(let [configured ((requiring-resolve '$resolver))] (if (string? configured) (print configured) (System/exit 64)))")"; then
    fail "$target does not configure :publish :mcp-config"
  fi
  [[ -n "$configured" ]] || fail "$target does not configure :publish :mcp-config"
  [[ "$configured" != *$'\n'* ]] \
    || fail "$target configured an invalid multiline MCP destination"
  mcp_resolved_destination="$(canonicalize_mcp_destination "$configured")" \
    || fail "$target configured an unresolvable MCP destination: $configured"
}

resolve_mcp_public_registry() {
  local registry_dir
  local target

  for target in "${targets[@]}"; do
    case "$target" in
      mcp-server|claude-server) ;;
      *) continue ;;
    esac
    resolve_mcp_target_destination "$target"
    if [[ -z "$mcp_public_registry" ]]; then
      mcp_public_registry="$mcp_resolved_destination"
    elif [[ "$mcp_resolved_destination" != "$mcp_public_registry" ]]; then
      fail "MCP-producing targets configure different canonical destinations: $mcp_public_registry and $mcp_resolved_destination"
    fi
  done

  [[ -n "$mcp_public_registry" ]] || fail "could not resolve the configured MCP destination"
  if [[ "${mcp_public_registry##*/}" == .mcp.json ]]; then
    registry_dir="${mcp_public_registry%/*}"
    mcp_ownership_alias="$registry_dir/.muse-host-targets-owners.json"
    mcp_lock_dir="$registry_dir/.muse-host-targets.lock"
    mcp_transaction_alias="$registry_dir/.muse-host-targets-transaction.json"
  else
    mcp_ownership_alias="$mcp_public_registry.muse-host-targets-owners.json"
    mcp_lock_dir="$mcp_public_registry.muse-host-targets.lock"
    mcp_transaction_alias="$mcp_public_registry.muse-host-targets-transaction.json"
  fi
  # State names are already derived from the canonical registry. Preserve the
  # documented ownership-sidecar link contract by binding its initial ultimate
  # target, then revalidate that logical alias throughout the build. Recovery
  # metadata itself stays at the fixed canonical-registry path so a later
  # writer cannot miss a retained marker after an ownership-alias change.
  mcp_ownership_file="$(canonicalize_mcp_destination "$mcp_ownership_alias")" \
    || fail "could not bind the MCP ownership destination"
  mcp_transaction_file="$(canonicalize_mcp_destination "$mcp_transaction_alias")" \
    || fail "could not bind the MCP transaction destination"
  [[ "$mcp_transaction_file" == "$mcp_transaction_alias" ]] \
    || fail "MCP transaction state path must not be a symlink: $mcp_transaction_alias"
  mcp_registry_dir="$(dirname "$mcp_public_registry")"
  mcp_ownership_dir="$(dirname "$mcp_ownership_file")"
  mcp_registry_dir_identity="$(directory_identity "$mcp_registry_dir")" \
    || fail "could not bind the MCP registry directory identity"
  mcp_ownership_dir_identity="$(directory_identity "$mcp_ownership_dir")" \
    || fail "could not bind the MCP ownership directory identity"
  mcp_lock_owner="$mcp_lock_dir/owner"
}

mcp_registry_lock_binding_matches() {
  local identity
  local owner

  if ! identity="$(directory_identity "$mcp_registry_dir" 2>/dev/null)"; then
    printf '[muse host build] could not revalidate MCP registry directory identity: %s\n' \
      "$mcp_registry_dir" >&2
    return 1
  fi
  if [[ "$identity" != "$mcp_registry_dir_identity" ]]; then
    printf '[muse host build] MCP registry directory identity changed after binding: expected %s, got %s\n' \
      "$mcp_registry_dir_identity" "$identity" >&2
    return 1
  fi
  if ((!mcp_lock_acquired)) || [[ -z "$mcp_lock_identity" ]]; then
    printf '[muse host build] MCP build lock identity is not bound\n' >&2
    return 1
  fi
  if ! identity="$(directory_identity "$mcp_lock_dir" 2>/dev/null)"; then
    printf '[muse host build] could not revalidate MCP build lock identity: %s\n' \
      "$mcp_lock_dir" >&2
    return 1
  fi
  if [[ "$identity" != "$mcp_lock_identity" ]]; then
    printf '[muse host build] MCP build lock identity changed after acquisition: expected %s, got %s\n' \
      "$mcp_lock_identity" "$identity" >&2
    return 1
  fi
  if ! owner="$(read_existing_mcp_lock_owner 2>/dev/null)"; then
    printf '[muse host build] MCP build lock owner is no longer a bounded regular record: %s\n' \
      "$mcp_lock_owner" >&2
    return 1
  fi
  if [[ "$owner" != "$$" ]]; then
    printf '[muse host build] MCP build lock owner changed after acquisition: expected %s, got %s\n' \
      "$$" "$owner" >&2
    return 1
  fi
  return 0
}

mcp_ownership_directory_binding_matches() {
  local identity

  if ! identity="$(directory_identity "$mcp_ownership_dir" 2>/dev/null)"; then
    printf '[muse host build] could not revalidate MCP ownership directory identity: %s\n' \
      "$mcp_ownership_dir" >&2
    return 1
  fi
  if [[ "$identity" != "$mcp_ownership_dir_identity" ]]; then
    printf '[muse host build] MCP ownership directory identity changed after binding: expected %s, got %s\n' \
      "$mcp_ownership_dir_identity" "$identity" >&2
    return 1
  fi
  return 0
}

mcp_namespace_bindings_match() {
  mcp_registry_lock_binding_matches \
    && mcp_ownership_directory_binding_matches
}

mcp_destination_namespace_bindings_match() {
  local destination="$1"

  case "$destination" in
    "$mcp_public_registry"|"$mcp_ownership_file")
      # A public-state operation must authenticate the complete pair, not only
      # the directory containing the pathname it happens to replace. In
      # particular, an ownership alias retargeted after transaction preparation
      # must stop both the registry and ownership publication paths.
      mcp_state_bindings_match
      ;;
    "$mcp_transaction_file")
      # The fixed recovery marker deliberately remains writable when the
      # ownership alias has changed, so cleanup can persist a rollback intent
      # that authenticates the originally bound ownership target.
      mcp_transaction_binding_matches
      ;;
    *)
      printf '[muse host build] refused an unbound MCP publication destination: %s\n' \
        "$destination" >&2
      return 1
      ;;
  esac
}

mcp_state_bindings_match() {
  local resolved

  mcp_namespace_bindings_match || return 1
  if ! resolved="$(canonicalize_mcp_destination "$mcp_public_registry")"; then
    printf '[muse host build] could not revalidate MCP registry path: %s\n' \
      "$mcp_public_registry" >&2
    return 1
  fi
  if [[ "$resolved" != "$mcp_public_registry" ]]; then
    printf '[muse host build] MCP registry path changed after binding: expected %s, got %s\n' \
      "$mcp_public_registry" "$resolved" >&2
    return 1
  fi

  if ! resolved="$(canonicalize_mcp_destination "$mcp_ownership_alias")"; then
    printf '[muse host build] could not revalidate MCP ownership state path: %s\n' \
      "$mcp_ownership_alias" >&2
    return 1
  fi
  if [[ "$resolved" != "$mcp_ownership_file" ]]; then
    printf '[muse host build] MCP ownership state path changed after binding: expected %s, got %s\n' \
      "$mcp_ownership_file" "$resolved" >&2
    return 1
  fi
  mcp_transaction_binding_matches
}

mcp_transaction_binding_matches() {
  local resolved

  mcp_registry_lock_binding_matches || return 1
  if ! resolved="$(canonicalize_mcp_destination "$mcp_transaction_alias")"; then
    printf '[muse host build] could not revalidate MCP transaction state path: %s\n' \
      "$mcp_transaction_alias" >&2
    return 1
  fi
  if [[ "$resolved" != "$mcp_transaction_file" ]]; then
    printf '[muse host build] MCP transaction state path changed after binding: expected %s, got %s\n' \
      "$mcp_transaction_file" "$resolved" >&2
    return 1
  fi
  return 0
}

verify_mcp_state_bindings() {
  mcp_state_bindings_match \
    || fail "MCP state destination binding changed during build"
}

verify_mcp_public_registry() {
  local target

  for target in "${targets[@]}"; do
    case "$target" in
      mcp-server|claude-server) ;;
      *) continue ;;
    esac
    resolve_mcp_target_destination "$target"
    [[ "$mcp_resolved_destination" == "$mcp_public_registry" ]] \
      || fail "$target configured MCP destination changed during build: expected $mcp_public_registry, got $mcp_resolved_destination"
  done
  verify_mcp_state_bindings
}

preflight_publish_destination() {
  local destination="$1"
  local destination_dir

  destination_dir="$(dirname "$destination")"
  mkdir -p -- "$destination_dir"
  node --input-type=module - "$destination" <<'NODE'
import {
  accessSync,
  constants,
  lstatSync,
  statSync,
} from "node:fs";
import {dirname} from "node:path";

const [destination] = process.argv.slice(2);
const existing = lstatSync(destination, {throwIfNoEntry: false});
if (existing?.isSymbolicLink()) {
  throw new Error(`${destination} changed to a symlink after binding`);
}
accessSync(dirname(destination), constants.W_OK);
if (existing) {
  const metadata = statSync(destination);
  const uid = process.getuid();
  if (metadata.uid !== uid) {
    throw new Error(`${destination} is owned by uid ${metadata.uid}; current uid is ${uid}`);
  }
  if (metadata.gid !== process.getgid() && !process.getgroups().includes(metadata.gid)) {
    throw new Error(`${destination} uses unavailable gid ${metadata.gid}`);
  }
}
NODE
}

# Registry bytes are visible to MCP clients, while ownership is private writer
# state. Persist and fsync the complete recovery pair before changing either.
# Single-target publication records its intended pair. A multi-target request
# instead retains the exact pre-command pair until every target and post-build
# hook succeeds, so interruption between targets rolls the whole request back.
# Failure rollback likewise replaces the marker before restoring exact bytes.
prepare_mcp_transaction() {
  local registry_source="$1"
  local registry_present="$2"
  local ownership_source="$3"
  local ownership_present="$4"

  if ! mcp_transaction_binding_matches \
      || [[ -L "$mcp_transaction_file" \
        || (-e "$mcp_transaction_file" && ! -f "$mcp_transaction_file") ]]; then
    return 1
  fi
  [[ -z "$mcp_transaction_record" ]] || rm -f -- "$mcp_transaction_record"
  mcp_transaction_record="$(mktemp)" || return 1
  if ! node --input-type=module - \
    "$mcp_transaction_record" \
    "$registry_source" \
    "$registry_present" \
    "$ownership_source" \
    "$ownership_present" \
    "$mcp_public_registry" \
    "$mcp_registry_dir_identity" \
    "$mcp_ownership_file" \
    "$mcp_ownership_dir_identity" <<'NODE'
import {createHash} from "node:crypto";
import {readFileSync, writeFileSync} from "node:fs";

const [
  output,
  registrySource,
  registryPresent,
  ownershipSource,
  ownershipPresent,
  registryPath,
  registryDirectoryIdentity,
  ownershipPath,
  ownershipDirectoryIdentity,
] = process.argv.slice(2);

function capture(path, present) {
  if (present === "0") return {present: false, sha256: null, bytes: null};
  if (present !== "1") throw new Error(`invalid transaction presence flag: ${present}`);
  const bytes = readFileSync(path);
  return {
    present: true,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    bytes: bytes.toString("base64"),
  };
}

const transaction = {
  version: 2,
  binding: {
    registryPath,
    registryDirectoryIdentity,
    ownershipPath,
    ownershipDirectoryIdentity,
  },
  registry: capture(registrySource, registryPresent),
  ownership: capture(ownershipSource, ownershipPresent),
};
writeFileSync(output, `${JSON.stringify(transaction)}\n`, {mode: 0o600});
NODE
  then
    return 1
  fi
  if ! mcp_transaction_binding_matches \
      || ! atomic_publish "$mcp_transaction_record" "$mcp_transaction_file" 600; then
    return 1
  fi
  rm -f -- "$mcp_transaction_record"
  mcp_transaction_record=""
}

publish_or_remove() {
  local source="$1"
  local present="$2"
  local destination="$3"

  case "$present" in
    1)
      atomic_publish "$source" "$destination"
      ;;
    0)
      remove_bound_destination "$destination"
      ;;
    *)
      return 1
      ;;
  esac
}

remove_bound_destination() {
  local destination="$1"

  mcp_destination_namespace_bindings_match "$destination" || return 1
  if ! node --input-type=module - "$destination" <<'NODE'
import {lstatSync, unlinkSync} from "node:fs";

const [destination] = process.argv.slice(2);
const existing = lstatSync(destination, {throwIfNoEntry: false});
if (!existing) process.exit(0);
if (!existing.isFile() || existing.isSymbolicLink()) {
  throw new Error(`${destination} changed to a nonregular destination after binding`);
}
unlinkSync(destination);
NODE
  then
    return 1
  fi
  sync -f -- "$(dirname "$destination")"
}

clear_mcp_transaction() {
  [[ -e "$mcp_transaction_file" || -L "$mcp_transaction_file" ]] || return 0
  [[ -f "$mcp_transaction_file" && ! -L "$mcp_transaction_file" ]] || return 1
  remove_bound_destination "$mcp_transaction_file"
}

apply_mcp_transaction() {
  local registry_source="$1"
  local registry_present="$2"
  local ownership_source="$3"
  local ownership_present="$4"
  local order="$5"

  case "$order" in
    registry-first)
      publish_or_remove "$registry_source" "$registry_present" "$mcp_public_registry" \
        && publish_or_remove "$ownership_source" "$ownership_present" "$mcp_ownership_file"
      ;;
    ownership-first)
      publish_or_remove "$ownership_source" "$ownership_present" "$mcp_ownership_file" \
        && publish_or_remove "$registry_source" "$registry_present" "$mcp_public_registry"
      ;;
    *)
      return 1
      ;;
  esac
}

recover_mcp_transaction() {
  local ownership_present
  local registry_present
  local state

  verify_mcp_state_bindings
  [[ -e "$mcp_transaction_file" || -L "$mcp_transaction_file" ]] || return 0
  [[ -f "$mcp_transaction_file" && ! -L "$mcp_transaction_file" ]] \
    || fail "MCP transaction marker is not a regular file: $mcp_transaction_file"
  mcp_recovery_registry="$(mktemp)" \
    || fail "could not allocate MCP transaction recovery storage"
  mcp_recovery_ownership="$(mktemp)" \
    || fail "could not allocate MCP transaction recovery storage"
  if ! state="$(node --input-type=module - \
    "$mcp_transaction_file" \
    "$mcp_recovery_registry" \
    "$mcp_recovery_ownership" \
    "$mcp_public_registry" \
    "$mcp_registry_dir_identity" \
    "$mcp_ownership_file" \
    "$mcp_ownership_dir_identity" \
    "$mcp_ownership_alias" <<'NODE'
import {createHash} from "node:crypto";
import {readFileSync, writeFileSync} from "node:fs";

const [
  transactionPath,
  registryOutput,
  ownershipOutput,
  registryPath,
  registryDirectoryIdentity,
  ownershipPath,
  ownershipDirectoryIdentity,
  ownershipAlias,
] = process.argv.slice(2);
const transaction = JSON.parse(readFileSync(transactionPath, "utf8"));

function objectMap(value) {
  return value && typeof value === "object" && !Array.isArray(value);
}

if (transaction?.version === 1) {
  if (ownershipAlias !== ownershipPath) {
    throw new Error(
      "legacy MCP transaction cannot authenticate a linked ownership target",
    );
  }
} else if (transaction?.version === 2) {
  if (!objectMap(transaction.binding)
      || transaction.binding.registryPath !== registryPath
      || transaction.binding.registryDirectoryIdentity !== registryDirectoryIdentity
      || transaction.binding.ownershipPath !== ownershipPath
      || transaction.binding.ownershipDirectoryIdentity !== ownershipDirectoryIdentity) {
    throw new Error("MCP transaction binding does not match the active publication namespace");
  }
} else {
  throw new Error("unsupported MCP transaction version");
}

function decode(label, state, output) {
  if (!objectMap(state) || typeof state.present !== "boolean") {
    throw new Error(`invalid ${label} transaction state`);
  }
  if (!state.present) {
    if (state.bytes !== null || state.sha256 !== null) {
      throw new Error(`invalid absent ${label} transaction state`);
    }
    return false;
  }
  if (typeof state.bytes !== "string" || typeof state.sha256 !== "string") {
    throw new Error(`invalid present ${label} transaction state`);
  }
  const bytes = Buffer.from(state.bytes, "base64");
  if (bytes.toString("base64") !== state.bytes) {
    throw new Error(`non-canonical ${label} transaction bytes`);
  }
  if (createHash("sha256").update(bytes).digest("hex") !== state.sha256) {
    throw new Error(`${label} transaction checksum mismatch`);
  }
  const value = JSON.parse(bytes.toString("utf8"));
  if (label === "registry") {
    if (!objectMap(value?.mcpServers)) {
      throw new Error("transaction registry must contain an mcpServers object");
    }
  } else {
    const targets = value?.targets;
    const valuesValid = objectMap(targets) && Object.values(targets).every(
      (name) => typeof name === "string" && name.length > 0,
    ) && new Set(Object.values(targets)).size === Object.values(targets).length;
    const keysValid = value?.version === 1
      ? Object.keys(targets ?? {}).every(
        (target) => /^[a-z0-9][a-z0-9-]*$/.test(target),
      )
      : value?.version === 2
        && Object.keys(targets ?? {}).every(
          (target) => /^[0-9a-f]{64}:[a-z0-9][a-z0-9-]*$/.test(target),
        );
    if (!valuesValid || !keysValid) {
      throw new Error("transaction ownership must contain a supported versioned targets object");
    }
  }
  writeFileSync(output, bytes, {mode: 0o600});
  return true;
}

const registryPresent = decode(
  "registry",
  transaction.registry,
  registryOutput,
);
const ownershipPresent = decode(
  "ownership",
  transaction.ownership,
  ownershipOutput,
);
process.stdout.write(`${registryPresent ? 1 : 0} ${ownershipPresent ? 1 : 0}`);
NODE
  )"; then
    fail "MCP transaction marker is invalid; preserve it for recovery: $mcp_transaction_file"
  fi
  read -r registry_present ownership_present <<< "$state"
  printf '[muse host build] recovering interrupted MCP state transaction\n'
  apply_mcp_transaction \
    "$mcp_recovery_registry" \
    "$registry_present" \
    "$mcp_recovery_ownership" \
    "$ownership_present" \
    registry-first \
    || fail "could not recover interrupted MCP state transaction"
  clear_mcp_transaction \
    || fail "could not clear recovered MCP transaction marker: $mcp_transaction_file"
}

publish_mcp_state() {
  verify_mcp_public_registry
  if ((mcp_target_count > 1)); then
    prepare_mcp_transaction \
      "$mcp_original_registry" \
      "$mcp_original_registry_present" \
      "$mcp_original_ownership" \
      "$mcp_original_ownership_present" \
      || fail "could not prepare MCP request rollback transaction"
    mcp_request_transaction_active=1
  else
    prepare_mcp_transaction "$mcp_registry" 1 "$mcp_ownership" 1 \
      || fail "could not prepare MCP state transaction"
  fi
  mcp_state_publication_started=1
  apply_mcp_transaction "$mcp_registry" 1 "$mcp_ownership" 1 registry-first \
    || fail "could not publish MCP state transaction"
  if ((mcp_target_count == 1)); then
    clear_mcp_transaction \
      || fail "could not clear completed MCP transaction marker: $mcp_transaction_file"
  fi
}

initialize_mcp_lock_owner() {
  node --input-type=module - \
    "$mcp_registry_dir" \
    "$mcp_registry_dir_identity" \
    "$mcp_lock_dir" \
    "$$" <<'NODE'
import {randomBytes} from "node:crypto";
import {
  closeSync,
  constants,
  fchmodSync,
  fstatSync,
  fsyncSync,
  linkSync,
  lstatSync,
  mkdirSync,
  openSync,
  readdirSync,
  rmdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import {basename, dirname} from "node:path";

const [
  registryDirectory,
  expectedRegistryIdentity,
  lockDirectory,
  ownerPid,
] = process.argv.slice(2);
const effectiveUid = BigInt(process.geteuid());

function existing(path) {
  return lstatSync(path, {bigint: true, throwIfNoEntry: false});
}

function identity(state) {
  return `${state.dev}:${state.ino}`;
}

function assertDirectory(path, expectedIdentity, label) {
  const state = existing(path);
  if (!state || !state.isDirectory() || state.isSymbolicLink()) {
    throw new Error(`${path} is not the bound ${label} directory`);
  }
  if (identity(state) !== expectedIdentity) {
    throw new Error(`${label} directory changed during owner initialization`);
  }
  return state;
}

function sameIdentity(left, right) {
  return left.dev === right.dev && left.ino === right.ino;
}

if (!/^[0-9]+$/.test(ownerPid)) {
  throw new Error("invalid MCP lock owner pid");
}
if (dirname(lockDirectory) !== registryDirectory) {
  throw new Error("MCP lock directory is outside the bound registry directory");
}

let registryDescriptor;
let lockDescriptor;
let ownerDescriptor;
let createdLock;
let createdOwner;
let boundLockDirectory;
let stagedOwner;
let ownerPath;
let initializationError;

try {
  assertDirectory(
    registryDirectory,
    expectedRegistryIdentity,
    "MCP registry",
  );
  registryDescriptor = openSync(
    registryDirectory,
    constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW,
  );
  const registryState = fstatSync(registryDescriptor, {bigint: true});
  if (!registryState.isDirectory()
      || identity(registryState) !== expectedRegistryIdentity) {
    throw new Error("MCP registry directory changed while pinning it");
  }

  const boundRegistryDirectory = `/proc/self/fd/${registryDescriptor}`;
  boundLockDirectory = `${boundRegistryDirectory}/${basename(lockDirectory)}`;
  mkdirSync(boundLockDirectory, {mode: 0o700});
  lockDescriptor = openSync(
    boundLockDirectory,
    constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW,
  );
  const lockState = fstatSync(lockDescriptor, {bigint: true});
  if (!lockState.isDirectory()
      || lockState.uid !== effectiveUid
      || (lockState.mode & 0o777n) !== 0o700n) {
    throw new Error("MCP lock directory is not the bound private lock");
  }
  assertDirectory(boundLockDirectory, identity(lockState), "MCP lock");
  // Only an effective-UID-owned, exact-mode directory whose pathname still
  // names the pinned descriptor gains cleanup authority. A replacement that
  // fails any check remains entirely untouched.
  createdLock = lockState;

  const boundLock = `/proc/self/fd/${lockDescriptor}`;
  stagedOwner = `${boundLock}/.owner.${ownerPid}.${randomBytes(16).toString("hex")}`;
  ownerPath = `${boundLock}/owner`;
  ownerDescriptor = openSync(
    stagedOwner,
    constants.O_WRONLY
      | constants.O_CREAT
      | constants.O_EXCL
      | constants.O_NOFOLLOW,
    0o600,
  );
  createdOwner = fstatSync(ownerDescriptor, {bigint: true});
  if (!createdOwner.isFile() || createdOwner.isSymbolicLink()) {
    throw new Error("staged MCP lock owner is not a regular file");
  }
  fchmodSync(ownerDescriptor, 0o600);
  const privateOwner = fstatSync(ownerDescriptor, {bigint: true});
  if (!sameIdentity(createdOwner, privateOwner)
      || privateOwner.uid !== effectiveUid
      || (privateOwner.mode & 0o777n) !== 0o600n) {
    throw new Error("staged MCP lock owner did not retain private ownership");
  }
  writeFileSync(ownerDescriptor, `${ownerPid}\n`, "utf8");
  fsyncSync(ownerDescriptor);

  assertDirectory(
    boundLockDirectory,
    identity(createdLock),
    "MCP lock",
  );
  linkSync(stagedOwner, ownerPath);
  const linkedOwner = existing(ownerPath);
  const stagedState = existing(stagedOwner);
  if (!linkedOwner
      || !stagedState
      || !sameIdentity(linkedOwner, createdOwner)
      || !sameIdentity(stagedState, createdOwner)) {
    throw new Error("MCP lock owner publication changed inode identity");
  }
  unlinkSync(stagedOwner);
  fsyncSync(lockDescriptor);
  fsyncSync(registryDescriptor);
} catch (error) {
  initializationError = error;
}

if (initializationError) {
  let cleanupError;

  // EEXIST means another invocation (or an operator-visible stale lock)
  // already owns the pathname. This invocation created nothing and therefore
  // has no deletion authority; let the shell classify the existing owner.
  if (initializationError?.code === "EEXIST" && createdLock === undefined) {
    if (registryDescriptor !== undefined) closeSync(registryDescriptor);
    process.exit(75);
  }

  try {
    // A failure before this invocation fstat-bound its private directory has
    // no deletion authority. Once bound, remove only this invocation's exact
    // owner inode, then remove the directory only if its original identity is
    // still at the bound pathname and the held descriptor proves it empty.
    if (createdLock && lockDescriptor !== undefined) {
      if (createdOwner) {
        const currentOwner = existing(ownerPath);
        const currentStage = existing(stagedOwner);
        if (currentOwner && !sameIdentity(currentOwner, createdOwner)) {
          throw new Error("refused to remove a substituted MCP lock owner");
        }
        if (currentStage && !sameIdentity(currentStage, createdOwner)) {
          throw new Error("refused to remove a substituted staged MCP lock owner");
        }
        if (currentOwner) unlinkSync(ownerPath);
        if (currentStage) unlinkSync(stagedOwner);
      }
      fsyncSync(lockDescriptor);
      if (readdirSync(`/proc/self/fd/${lockDescriptor}`).length !== 0) {
        throw new Error("refused to remove a nonempty MCP lock directory");
      }

      closeSync(lockDescriptor);
      lockDescriptor = undefined;
      assertDirectory(
        boundLockDirectory,
        identity(createdLock),
        "MCP lock",
      );
      rmdirSync(boundLockDirectory);
      fsyncSync(registryDescriptor);
    }
  } catch (error) {
    cleanupError = error;
  }

  if (ownerDescriptor !== undefined) closeSync(ownerDescriptor);
  if (lockDescriptor !== undefined) closeSync(lockDescriptor);
  if (registryDescriptor !== undefined) closeSync(registryDescriptor);
  if (cleanupError) {
    throw new AggregateError(
      [initializationError, cleanupError],
      "refused unsafe cleanup of failed MCP lock initialization",
    );
  }
  throw initializationError;
}

closeSync(ownerDescriptor);
closeSync(lockDescriptor);
closeSync(registryDescriptor);
process.stdout.write(identity(createdLock));
NODE
}

read_existing_mcp_lock_owner() {
  node --input-type=module - "$mcp_lock_owner" <<'NODE'
import {
  closeSync,
  constants,
  fstatSync,
  openSync,
  readSync,
} from "node:fs";

const [ownerPath] = process.argv.slice(2);
const maximumRecordBytes = 32;
let descriptor;

try {
  try {
    descriptor = openSync(
      ownerPath,
      constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK,
    );
  } catch (error) {
    // A newly published owner may not be visible on the first contention
    // probe. Only absence is retryable; links, permissions, and other object
    // types are immediately an invalid fail-closed record.
    process.exit(error?.code === "ENOENT" ? 75 : 76);
  }

  const before = fstatSync(descriptor, {bigint: true});
  if (!before.isFile()
      || before.size < 2n
      || before.size > BigInt(maximumRecordBytes)) {
    process.exit(76);
  }

  // Read at most one byte beyond the contract so a concurrently enlarged
  // record cannot turn this classification probe into unbounded input.
  const bytes = Buffer.alloc(maximumRecordBytes + 1);
  let length = 0;
  while (length < bytes.length) {
    const count = readSync(
      descriptor,
      bytes,
      length,
      bytes.length - length,
      null,
    );
    if (count === 0) break;
    length += count;
  }
  const after = fstatSync(descriptor, {bigint: true});
  if (after.dev !== before.dev
      || after.ino !== before.ino
      || after.size !== before.size
      || BigInt(length) !== before.size) {
    process.exit(76);
  }

  const record = bytes.subarray(0, length).toString("utf8");
  const match = /^([1-9][0-9]*)\n$/.exec(record);
  if (!match || BigInt(match[1]) > 2147483647n) process.exit(76);
  process.stdout.write(match[1]);
} finally {
  if (descriptor !== undefined) closeSync(descriptor);
}
NODE
}

acquire_mcp_build_lock() {
  local attempt
  local initialize_status
  local owner
  local owner_status

  set +e
  mcp_lock_identity="$(umask 077; initialize_mcp_lock_owner)"
  initialize_status="$?"
  set -e
  if ((initialize_status == 0)); then
    # Success means the one initializer process created, fstat-bound, and
    # recorded ownership in the private directory. Mark it acquired before
    # validating stdout so every later refusal flows through guarded cleanup.
    mcp_lock_acquired=1
    [[ "$mcp_lock_identity" =~ ^[0-9]+:[0-9]+$ ]] \
      || fail "could not bind the new MCP build lock identity"
    mcp_namespace_bindings_match \
      || fail "MCP publication namespace changed while acquiring the build lock"
    return
  fi
  if ((initialize_status != 75)); then
    fail "could not create, bind, and record ownership of the MCP build lock: $mcp_lock_dir"
  fi

  [[ -d "$mcp_lock_dir" ]] || fail "could not create the MCP build lock: $mcp_lock_dir"
  owner=""
  for ((attempt = 1; attempt <= 5; attempt++)); do
    set +e
    owner="$(read_existing_mcp_lock_owner 2>/dev/null)"
    owner_status="$?"
    set -e
    if ((owner_status == 0)); then
      break
    fi
    if ((owner_status != 75)); then
      fail "MCP build lock has no valid owner; remove $mcp_lock_dir only after verifying no build is active"
    fi
    sleep 0.05
  done
  if [[ "$owner" =~ ^[0-9]+$ ]] && kill -0 "$owner" 2>/dev/null; then
    fail "another MCP-producing build is active (pid $owner)"
  fi
  if [[ "$owner" =~ ^[0-9]+$ ]]; then
    fail "stale MCP build lock owned by dead pid $owner; remove $mcp_lock_dir only after verifying no build is active"
  fi
  fail "MCP build lock has no valid owner; remove $mcp_lock_dir only after verifying no build is active"
}

cleanup_mcp_registry() {
  local exit_status=$?
  local lock_release_failed=0
  local registry_restored=0
  local rollback_prepared=0
  local ownership_restored=0
  local state_bindings_valid=0
  local temp
  set +e
  trap - EXIT

  if ((exit_status != 0 \
      && mcp_state_restore_ready \
      && mcp_state_publication_started)); then
    if mcp_transaction_binding_matches \
        && prepare_mcp_transaction \
      "$mcp_original_registry" \
      "$mcp_original_registry_present" \
      "$mcp_original_ownership" \
      "$mcp_original_ownership_present"; then
      rollback_prepared=1
    else
      printf '[muse host build] failed to prepare MCP rollback transaction\n' >&2
    fi

    if ((rollback_prepared)); then
      if mcp_state_bindings_match; then
        state_bindings_valid=1
      else
        printf '[muse host build] skipped MCP rollback because a state destination binding changed\n' >&2
      fi

      if ((state_bindings_valid)); then
        if publish_or_remove \
          "$mcp_original_ownership" \
          "$mcp_original_ownership_present" \
          "$mcp_ownership_file"; then
          ownership_restored=1
        else
          if ((mcp_original_ownership_present)); then
            printf '[muse host build] failed to restore %s\n' "$mcp_ownership_file" >&2
          else
            printf '[muse host build] failed to remove partial %s\n' "$mcp_ownership_file" >&2
          fi
        fi

        if ((ownership_restored)); then
          if publish_or_remove \
            "$mcp_original_registry" \
            "$mcp_original_registry_present" \
            "$mcp_public_registry"; then
            registry_restored=1
          elif ((mcp_original_registry_present)); then
            printf '[muse host build] failed to restore %s\n' "$mcp_public_registry" >&2
          else
            printf '[muse host build] failed to remove partial %s\n' "$mcp_public_registry" >&2
          fi
        else
          printf '[muse host build] skipped registry rollback because ownership rollback failed\n' >&2
        fi
      fi

      if ((state_bindings_valid && ownership_restored && registry_restored)); then
        clear_mcp_transaction \
          || printf '[muse host build] failed to clear completed MCP rollback transaction\n' >&2
      else
        printf '[muse host build] preserved MCP rollback transaction for recovery: %s\n' \
          "$mcp_transaction_file" >&2
      fi
    fi
  fi

  for temp in \
    "$mcp_registry" \
    "$generated_mcp_registry" \
    "$mcp_generated_output" \
    "$mcp_ownership" \
    "$mcp_original_registry" \
    "$mcp_original_ownership" \
    "$mcp_transaction_record" \
    "$mcp_recovery_registry" \
    "$mcp_recovery_ownership"; do
    [[ -z "$temp" ]] || rm -f -- "$temp"
  done

  if ((mcp_lock_acquired)); then
    if mcp_state_bindings_match; then
      if ! rm -f -- "$mcp_lock_owner"; then
        printf '[muse host build] failed to remove lock owner %s\n' "$mcp_lock_owner" >&2
        lock_release_failed=1
      fi
      if ! rmdir -- "$mcp_lock_dir"; then
        printf '[muse host build] failed to release %s\n' "$mcp_lock_dir" >&2
        lock_release_failed=1
      fi
    else
      printf '[muse host build] refused to release the MCP build lock because its namespace binding changed\n' >&2
      lock_release_failed=1
    fi
  fi

  if ((lock_release_failed && exit_status == 0)); then
    exit_status=64
  fi

  exit "$exit_status"
}

if ((mcp_target_count > 0)); then
  # Reject an absent or invalid publication contract before creating any
  # producer identity, lock, generated source, or destination-side state.
  resolve_mcp_public_registry
  # One private, durable token follows the checkout when its root moves.
  # Physical path aliases read the same file, while separate checkouts create
  # distinct ownership keys even when they publish to one shared registry.
  mcp_producer_id="$(resolve_mcp_producer_identity)" \
    || fail "could not resolve the stable MCP producer identity"
  trap cleanup_mcp_registry EXIT
  acquire_mcp_build_lock
  preflight_publish_destination "$mcp_public_registry" \
    || fail "configured MCP destination failed ownership/write preflight: $mcp_public_registry"
  preflight_publish_destination "$mcp_ownership_file" \
    || fail "MCP ownership destination failed ownership/write preflight: $mcp_ownership_file"
  preflight_publish_destination "$mcp_transaction_file" \
    || fail "MCP transaction destination failed ownership/write preflight: $mcp_transaction_file"
  recover_mcp_transaction
  verify_mcp_state_bindings
  mcp_registry="$(mktemp)"
  generated_mcp_registry="$(mktemp)"
  mcp_generated_output="$(mktemp)"
  mcp_ownership="$(mktemp)"
  mcp_original_registry="$(mktemp)"
  mcp_original_ownership="$(mktemp)"
  if [[ -e "$mcp_public_registry" || -L "$mcp_public_registry" ]]; then
    cp "$mcp_public_registry" "$mcp_original_registry"
    mcp_original_registry_present=1
    cp "$mcp_original_registry" "$mcp_registry"
  else
    printf '%s\n' '{"mcpServers":{}}' > "$mcp_registry"
  fi
  if [[ -e "$mcp_ownership_file" || -L "$mcp_ownership_file" ]]; then
    cp "$mcp_ownership_file" "$mcp_original_ownership"
    mcp_original_ownership_present=1
    cp "$mcp_original_ownership" "$mcp_ownership"
  else
    printf '%s\n' '{"version":1,"targets":{}}' > "$mcp_ownership"
  fi
  if node --input-type=module - "$mcp_ownership" <<'NODE'
import {readFileSync} from "node:fs";

const [ownershipPath] = process.argv.slice(2);
const ownership = JSON.parse(readFileSync(ownershipPath, "utf8"));
if (ownership?.version !== 1) process.exit(1);
NODE
  then
    mcp_legacy_relative_migration=1
  fi
  mcp_state_restore_ready=1
  printf '%s\n' '{"mcpServers":{}}' > "$generated_mcp_registry"
fi

merge_mcp_registration() {
  local target="$1"
  local generated_registry="$mcp_generated_output"
  [[ -s "$generated_registry" ]] || fail "host build did not publish $generated_registry"

  node --input-type=module - \
    "$mcp_registry" \
    "$generated_registry" \
    "$generated_mcp_registry" \
    "$mcp_ownership" \
    "$target" \
    "$mcp_producer_id" \
    "$repo_root" \
    "$mcp_legacy_relative_migration" \
    "${mcp_requested_targets[@]}" <<'NODE'
import {readFileSync, writeFileSync} from "node:fs";
import {isAbsolute, resolve} from "node:path";
import {isDeepStrictEqual} from "node:util";

const [
  accumulatorPath,
  generatedPath,
  generatedThisRequestPath,
  ownershipPath,
  target,
  producerId,
  producerRoot,
  allowLegacyRelativeMigration,
  ...requestedTargets
] = process.argv.slice(2);
const legacyProducerId = "0".repeat(64);

function registrations(path) {
  const value = JSON.parse(readFileSync(path, "utf8"));
  const servers = value?.mcpServers;
  if (!servers || typeof servers !== "object" || Array.isArray(servers)) {
    throw new Error(`${path} must contain an mcpServers object`);
  }
  return servers;
}

function targetOwnership(path) {
  const value = JSON.parse(readFileSync(path, "utf8"));
  const targets = value?.targets;
  if (!targets
      || typeof targets !== "object"
      || Array.isArray(targets)
      || Object.values(targets).some((name) => typeof name !== "string" || name.length === 0)
      || new Set(Object.values(targets)).size !== Object.values(targets).length) {
    throw new Error(`${path} must contain a supported versioned targets object`);
  }
  if (value?.version === 1) {
    if (Object.keys(targets).some(
      (ownedTarget) => !/^[a-z0-9][a-z0-9-]*$/.test(ownedTarget),
    )) {
      throw new Error(`${path} contains an invalid legacy target key`);
    }
    return Object.fromEntries(
      Object.entries(targets).map(
        ([ownedTarget, name]) => [`${legacyProducerId}:${ownedTarget}`, name],
      ),
    );
  }
  if (value?.version !== 2
      || Object.keys(targets).some(
        (ownedTarget) => !/^[0-9a-f]{64}:[a-z0-9][a-z0-9-]*$/.test(ownedTarget),
      )) {
    throw new Error(`${path} must contain a supported versioned targets object`);
  }
  return targets;
}

if (!/^[0-9a-f]{64}$/.test(producerId) || producerId === legacyProducerId) {
  throw new Error(`invalid MCP producer identity: ${producerId}`);
}
if (!isAbsolute(producerRoot) || resolve(producerRoot) !== producerRoot) {
  throw new Error(`invalid MCP producer root: ${producerRoot}`);
}
if (allowLegacyRelativeMigration !== "0" && allowLegacyRelativeMigration !== "1") {
  throw new Error("invalid legacy relative-registration migration policy");
}
if (requestedTargets.length === 0
    || !requestedTargets.includes(target)
    || requestedTargets.some(
      (requestedTarget) => requestedTarget !== "mcp-server"
        && requestedTarget !== "claude-server",
    )) {
  throw new Error("invalid requested MCP producer target set");
}
const requestedOwnershipKeys = new Set(
  requestedTargets.map((requestedTarget) => `${producerId}:${requestedTarget}`),
);

function bindRegistrationToProducer(registration) {
  if (!registration
      || typeof registration !== "object"
      || Array.isArray(registration)
      || registration.command !== "node"
      || !Array.isArray(registration.args)
      || registration.args.length === 0
      || typeof registration.args[0] !== "string"
      || registration.args[0].length === 0) {
    throw new Error("generated MCP registration must launch one node entrypoint");
  }
  const args = [...registration.args];
  // Hook output is relative to the checkout. The public registry may be
  // shared by several checkouts and consumed from an unrelated working
  // directory, so make the producing checkout part of the launch contract.
  args[0] = resolve(producerRoot, args[0]);
  return {...registration, args};
}

const merged = Object.assign(Object.create(null), registrations(accumulatorPath));
const generatedThisRequest = Object.assign(
  Object.create(null),
  registrations(generatedThisRequestPath),
);
const ownership = Object.assign(
  Object.create(null),
  targetOwnership(ownershipPath),
);
const generatedEntries = Object.entries(registrations(generatedPath));
if (generatedEntries.length !== 1) {
  throw new Error(`${generatedPath} must contain exactly one generated MCP registration`);
}

for (const [name, generatedRegistration] of generatedEntries) {
  const registration = bindRegistrationToProducer(generatedRegistration);
  if (Object.hasOwn(generatedThisRequest, name)
      && !isDeepStrictEqual(generatedThisRequest[name], registration)) {
    throw new Error(`conflicting MCP registration: ${name}`);
  }

  const ownershipKey = `${producerId}:${target}`;
  const legacyOwnershipKey = `${legacyProducerId}:${target}`;
  let legacyNameTransferred = false;
  let requestedNameTransferred = false;
  for (const [ownedTarget, ownedName] of Object.entries(ownership)) {
    if (ownedTarget !== ownershipKey && ownedName === name) {
      if (ownedTarget === legacyOwnershipKey) {
        delete ownership[ownedTarget];
        legacyNameTransferred = true;
      } else if (requestedOwnershipKeys.has(ownedTarget)) {
        if (Object.hasOwn(generatedThisRequest, name)) {
          throw new Error(`conflicting MCP registration: ${name}`);
        }
        // A multi-target request may coordinate a name swap. Relinquish only
        // another target owned by this producer and named in this request;
        // a later build failure rolls the complete request back to its exact
        // pre-command registry and ownership snapshots.
        delete ownership[ownedTarget];
        requestedNameTransferred = true;
      } else {
        throw new Error(`MCP registration ${name} is already owned by producer target ${ownedTarget}`);
      }
    }
  }

  const previousName = ownership[ownershipKey];
  const currentNameOwned = previousName === name;
  const exactLegacyRelativeMatch = allowLegacyRelativeMigration === "1"
    && Object.hasOwn(merged, name)
    && isDeepStrictEqual(merged[name], generatedRegistration);
  if (Object.hasOwn(merged, name)
      && !currentNameOwned
      && !legacyNameTransferred
      && !requestedNameTransferred
      && !exactLegacyRelativeMatch
      && !isDeepStrictEqual(merged[name], registration)) {
    throw new Error(`unowned MCP registration ${name} conflicts with generated output`);
  }
  if (previousName) {
    if (previousName !== name) {
      delete merged[previousName];
    }
  }

  generatedThisRequest[name] = registration;
  merged[name] = registration;
  ownership[ownershipKey] = name;
}

const sorted = Object.fromEntries(Object.keys(merged).sort().map((name) => [name, merged[name]]));
const sortedGenerated = Object.fromEntries(
  Object.keys(generatedThisRequest).sort().map((name) => [name, generatedThisRequest[name]]),
);
const sortedOwnership = Object.fromEntries(
  Object.keys(ownership).sort().map((ownedTarget) => [ownedTarget, ownership[ownedTarget]]),
);
writeFileSync(accumulatorPath, `${JSON.stringify({mcpServers: sorted}, null, 2)}\n`);
writeFileSync(
  generatedThisRequestPath,
  `${JSON.stringify({mcpServers: sortedGenerated}, null, 2)}\n`,
);
writeFileSync(
  ownershipPath,
  `${JSON.stringify({version: 2, targets: sortedOwnership}, null, 2)}\n`,
);
NODE
}

build_target() {
  local target="$1"
  local generator
  local entrypoint

  case "$target" in
    opencode-plugin)
      generator="eta-mu.opencode.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/opencode_plugin.cljs"
      ;;
    mcp-server)
      generator="eta-mu.mcp.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/mcp_server.cljs"
      ;;
    claude-server)
      generator="eta-mu.claude.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/claude_server.cljs"
      ;;
  esac

  printf '[muse host build] generating %s from .ημ/config\n' "$entrypoint"
  clojure -M -e "((requiring-resolve '$generator) {})"
  [[ -s "$entrypoint" ]] || fail "generator did not write $entrypoint"

  printf '[muse host build] releasing %s\n' "$target"
  case "$target" in
    mcp-server|claude-server)
      : > "$mcp_generated_output"
      # A persistent Shadow server keeps its startup environment. Force this
      # release into a fresh JVM so the hook always receives this invocation's
      # private output path instead of falling back to the live registry.
      MUSE_MCP_CONFIG_OUTPUT="$mcp_generated_output" \
        "$shadow" release "$target" --force-spawn
      ;;
    *)
      # A server started before src/gen existed cannot discover the new
      # OpenCode namespace through its startup classpath. Use a fresh JVM
      # after generation, just as the MCP-producing releases do.
      "$shadow" release "$target" --force-spawn
      ;;
  esac

  if [[ -n "$mcp_registry" ]]; then
    case "$target" in
      mcp-server|claude-server)
        verify_mcp_public_registry
        merge_mcp_registration "$target"
        publish_mcp_state
        ;;
    esac
  fi

  if [[ "$target" == claude-server ]]; then
    printf '[muse host build] emitting Claude hook configuration\n'
    node .claude/dist/claude-server.js --emit-hook-config
  fi
}

for target in "${targets[@]}"; do
  build_target "$target"
done

if ((mcp_request_transaction_active)); then
  clear_mcp_transaction \
    || fail "could not clear completed MCP request rollback marker: $mcp_transaction_file"
  mcp_request_transaction_active=0
fi
